### ISSUE TITLE
RNHyperTrack is undefined

### ISSUE THREAD

**Issue by zbluhm** [hypertrack/react-native-hypertrack#14]
Issue: Testing app using android with HyperTrack installed via npm and linked with react fails to run. The issue appears to stem from the module itself, specifically line 13 of index.js
`    // Method to intialize the SDK with publishable key
    initialize(token) {
        RNHyperTrack.initialize(token);
    },`

This line produces the following error: "undefined is not an object (evaluating 'RNHyperTrack.initialize')"

Steps to reproduce:
1. Init new react project
2. Install hypertrack - npm install react-native-hypertrack --save
3. Link - react-native link react-native-hypertrack 
4. Follow get started guide to import necessary modules and initialize HyperTrack and add dependency to gradle build file.
5. Reload app

Please let me know if I can add any other information to help fix this issue

**Comment by arjun27** [comment]
Hey @zbluhm, sorry that you had to face this issue. It looks like a case of broken linking. Can you confirm the react native version you are using?

We used to have a troubleshoot guide for Android for specifically this issue - we removed it since the newer versions of react native had reliable auto-linking for libraries. I pulled out the guide for you, can you try these steps out: https://github.com/hypertrack/react-native-hypertrack/blob/0bb76c2a264719ca937bc9ea79c7a71c994db183/android-troubleshooting.md

**Comment by zbluhm** [comment]
Thanks for the response, here are the contents of my package.json file:
`{
  "name": "untitled",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-hypertrack": "^1.3.9"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "3.0.1",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

I followed the undefined methods part of the guide and all of the files already contained the lines I was supposed to add.

**Comment by arjun27** [comment]
Thanks. There seems to be an issue with the NativeModules setup. A simple console log will help us diagnose what's going on

```
import { NativeModules } from 'react-native'
console.log(NativeModules)
```

**Comment by zbluhm** [comment]
Well - I'm now getting the following error on build:

> :react-native-hypertrack:prepareComAndroidVolleyVolley100Library FAILED

**Comment by zbluhm** [comment]
Okay I got everything working... You guys need to update your starting documentation here: https://dashboard.hypertrack.com/onboarding/sdk-reactnative;step=0.1 so that it is equal to your set up documentation on github.

Particularly this bit is missing from the onboarding: 

> In your android/app/build.gradle file, update the following:

    compileSdkVersion 25
    buildToolsVersion "25.0.1"

**Comment by arjun27** [comment]
Updating docs with this resolution. Thanks @zbluhm
