### ISSUE TITLE
Gradle sync fails with "Failed to resolve: com.hypertrack:android:0.7.37"

### ISSUE THREAD

**Issue by srishanbhattarai** [hypertrack/react-native-hypertrack#24]
I've fully followed the documentation and I get this error on Android. Would appreciate guidance on what information would be helpful to you to debug this.

**Comment by ravijain412** [comment]
@srishanbhattarai: Have you added to maven url in your build.gradle?

**Comment by srishanbhattarai** [comment]
Related to https://github.com/hypertrack/react-native-hypertrack/issues/23
Safe to close this.
