### ISSUE TITLE
Packaging the library in a different namespace to avoid predex or library build collisions with other native packages

### ISSUE THREAD

**Issue by wiresurfer** [hypertrack/react-native-hypertrack#4]
Using the default package name "com.reactlibrary"
leads to collisions with other native libs 
[Who , I admit, should namespace better]

1) Changes would be folder structure, 
2) package names and imports
3) Relevant changes for react-native link..

**Comment by arjun27** [comment]
@wiresurfer, thanks for reporting this. Let me get this out in 0.3.0

**Comment by arjun27** [comment]
Fixed in https://github.com/hypertrack/react-native-hypertrack/commit/dfeb0893afe32b406ea874fbefd32c54aab2acdd
