### ISSUE TITLE
Missing APIs in RNHyperTrackModule

### ISSUE THREAD

**Issue by piyushgupta27** [hypertrack/react-native-hypertrack#6]
The RNHyperTrackModule doesn't have the following APIs:

1. DriverSDK State APIs like `isDriverLive`, `getDriverID`etc.
2. `startLocationService`, `refreshTrip`, `refreshTask` APIs
3. Intents for Service or Trip or Shift started/ended
4. ServiceNotification Customization APIs

**Comment by arjun27** [comment]
startLocationService (#2) and the intents in point 3 have been released

**Comment by arjun27** [comment]
Closing this as v1.0.0 released for the new re-designed native SDKs
